spring.application.name=VinylShop

#POSTGRESQL_DATABASENAME = vinylshop
#POSTGRESQL_USERNAME = postgres
#POSTGRESQL_PASSWORD = geheim

# Database url, username en password aanpassen aan jouw configuratie:
# - Vul ze hier "hardcoded" in.
# - Vul de parameters in de run environment in.
# - Maak variabelen zoals:
#       - POSTGRESQL_DATABASENAME = testing
#       - POSTGRESQL_USERNAME = postgres
#       - POSTGRESQL_PASSWORD = geheim
spring.datasource.url=jdbc:postgresql://localhost:5432/security
#  ${POSTGRESQL_DATABASENAME}
spring.datasource.username=postgres
spring.datasource.password=password

# Jpa instellingen
spring.jpa.show-sql=true

# forces to generate the data structures
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# database initialization with data.sql after hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#keycloak
client-id=vinylshopbackend
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/vinylshop
spring.security.oauth2.resourceserver.jwt.audience=account
client-secret = t8HAOrjdXqtKFBreLhn14DtgGqSdKCSl0JQZyn10beo48a1sbA1QN3qhzHMz5nlrUMdoEtBjmePw8VOUGGy2F3


